Working around JBoss5 problem. See the stack trace below:
SEVERE: Failed to execute command close
java.lang.UnsatisfiedLinkError: Unable to load winp.dll
        at org.jvnet.winp.Native.load(Native.java:121)
        at org.jvnet.winp.Native.<clinit>(Native.java:49)
        at
org.jvnet.winp.WinProcess.enableDebugPrivilege(WinProcess.java
        at
hudson.util.ProcessTreeKiller$Windows.<clinit>(ProcessTreeKill
        at hudson.util.ProcessTreeKiller.get(ProcessTreeKiller.java:91)
        at hudson.Proc$LocalProc.destroy(Proc.java:166)
        at hudson.Proc$LocalProc.kill(Proc.java:158)
        at
hudson.maven.MavenProcessFactory$1.terminate(MavenProcessFacto
        at
hudson.remoting.Channel$CloseCommand.execute(Channel.java:554)
        at hudson.remoting.Channel$ReaderThread.run(Channel.java:647)
Caused by: java.lang.UnsatisfiedLinkError: no winp in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1682)
        at java.lang.Runtime.loadLibrary0(Runtime.java:822)
        at java.lang.System.loadLibrary(System.java:993)
        at org.jvnet.winp.Native.load(Native.java:119)
        ... 9 more
12:36:11,107 ERROR [STDERR] 02-Feb-2009 12:36:11
hudson.remoting.Channel$
SEVERE: This command is created here
Command close created at
        at hudson.remoting.Command.<init>(Command.java:24)
        at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:550)
        at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:550)
        at hudson.remoting.Channel.close(Channel.java:594)
        at
hudson.remoting.Channel$CloseCommand.execute(Channel.java:553)
        at hudson.remoting.Channel$ReaderThread.run(Channel.java:647)
12:36:28,674 ERROR [STDERR] 02-Feb-2009 12:36:28
hudson.remoting.Channel$
SEVERE: Failed to execute command close
java.lang.NoClassDefFoundError
        at hudson.util.ProcessTreeKiller.get(ProcessTreeKiller.java:91)
        at hudson.Proc$LocalProc.destroy(Proc.java:166)
        at hudson.Proc$LocalProc.kill(Proc.java:158)
        at
hudson.maven.MavenProcessFactory$1.terminate(MavenProcessFacto
        at
hudson.remoting.Channel$CloseCommand.execute(Channel.java:554)
        at hudson.remoting.Channel$ReaderThread.run(Channel.java:647)